# Generated by Django 4.2.3 on 2023-07-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="subjects",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="udemy",
            options={"managed": True},
        ),
    ]
